//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Carreras.java
//  @ Date : 23/05/2014
//  @ Author : 
//
//




public class Carreras {
	private Object Estudiantes;
	private String Nombre;
	public Escuela 0;
	public Estudiante 0...*;
}
