//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Escuela.java
//  @ Date : 23/05/2014
//  @ Author : 
//
//




public class Escuela {
	private Object Carreras;
	private int NumEst;
	private String Nombre;
	public UniversidadEafit 1;
}
