//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Estudiante.java
//  @ Date : 23/05/2014
//  @ Author : 
//
//




public class Estudiante extends Persona {
	private Object Codigo;
	private Object Carreras;
	private Bool candidatos;
	public Carreras 1...*;
	public void Votar() {
	
	}
}
