//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Persona.java
//  @ Date : 23/05/2014
//  @ Author : 
//
//




public abstract class Persona {
	private String Nombre;
	private String Correo;
	private Object Password;
}
