//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : UniversidadEafit.java
//  @ Date : 23/05/2014
//  @ Author : 
//
//




public class UniversidadEafit {
	private Escuela escuelas;
	private String puestosV;
	private UniversidadEafit votaciones;
	public Escuela 1...*;
}
