//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Votaciones.java
//  @ Date : 23/05/2014
//  @ Author : 
//
//




public class Votaciones {
	private Object FechaInicio;
	private Object FechaFin;
	private Voto Votos;
	private Candidatos candidatos;
	private String Nombre;
	public UniversidadEafit 1;
}
