//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Voto.java
//  @ Date : 23/05/2014
//  @ Author : 
//
//




public class Voto {
	private String PuestoVotacion;
	private Estudiante Votante;
	private Estudiante Seleccion;
}
